version: "3"

services: 
    nowruz: 
        user: $UID:$GID
        build:
            context: .
        ports:
            - "8000:8000"
        volumes: 
            - ./nowruzWebsite:/nowruzWebsite:Z
        command: >
         sh -c "python3.7 manage.py wait_for_db &&
                python3.7 manage.py migrate &&
                python3.7 manage.py runserver 0.0.0.0:8000"

        environment:
            - DB_HOST=db
            - DB_NAME=nowruz
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
        depends_on: 
            - db 

    db:
        image: postgres:10-alpine
        environment:
            - POSTGRES_DB=nowruz
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
        
